// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    double genaratedNum = Math.random();;
		int count = 0;
		int smallCount = 0;
		int largeCount = 0;
		double ratio;
		while (count < 100) {
			if (genaratedNum > 0.5) {
				count++;
				largeCount++;
			genaratedNum = Math.random(); 
				continue;
			}
			else {
			count++;
			smallCount++;
			genaratedNum = Math.random();
			}
			
			
		}
		System.out.println("> 0.5: " +largeCount);
		System.out.println("<= 0.5: " +smallCount);
        System.out.println("Ratio: " + ((double) largeCount/smallCount));
	}
}
